### ISSUE TITLE
Ordner für die Settings ist nicht Standard

### ISSUE THREAD

**Issue by 112TEC-Chris** [sperrgebiet/FS22_VehicleExplorer#11]
Hallo,
das ist zwar nur ne Kleinigkeit, aber doch etwas störend:
Die Einstellungen werden in modssettings gespeichert, aber standardmässig gibt es einen Ordner modsettings, also nur mit einem s in der Mitte. Es wäre schön, wenn das angepasst würde.

**Comment by sperrgebiet** [comment]
Servus. Danke. War eines der Dinge dir mir auch gleich mal aufgefallen ist, ich bei allen adneren mods richtig gezogen hab, nur hier eben noch nicht ;)  Hab ich grad gmacht.
glG
_Has
