### ISSUE TITLE
Doesn't show vehicle list, when attaching a bigbag to Quicke Big Bag Lifter 

### ISSUE THREAD

**Issue by Mexel75** [sperrgebiet/FS22_VehicleExplorer#15]
When attaching a bigbag to Quicke Big Bag Lifter (single or dual), the vehicle list becomes empty. As soon as the bigbag has been detached, the list is back.

Log file error:
VehicleSort.lua:813: attempt to call method 'getAttachedImplements' (a nil value)

**Comment by sperrgebiet** [comment]
Thanks. Actually that one was closed quite some time. I just never did a update here in Github. Shame on me :/
