### ISSUE TITLE
Paint/repair

### ISSUE THREAD

**Issue by Binolyen** [sperrgebiet/FS22_VehicleExplorer#5]
Thank you for this and Tardis.

The wear percentage in the vehicle information window is not accurate with the new paint features of FS22.  If it's possible it would be great if there was a second line of information showing the paint wear and the maintenance wear was shown separately and accurately.

Again, thanks for getting this out so quickly.

**Comment by sperrgebiet** [comment]
Hi

Well, I got it out relatively quickly, just recently there weren't a lot of updates, at least none I pushed to Github. So shame on me ;)
But the wear and damage is now visible seperately. And simliar like in FS19 with Seasons, within the settings you can enable/disable if ou want to repaint the vehicle or just repair it.

HTH
_Hans
